### ISSUE TITLE
Things noticed on the first basic example

### ISSUE THREAD

**Issue by helio-frota** [helio-frota/nodeshift-playground#1]
* I added nodeshift on `start` script for the first time **by mistake**, and got an error "nodeshift not found" or something after a successful deploy

```
"scripts": {
    "start": "NODE_DEBUG=dbg-* nodeshift"
  },
```

Then changed to :

```
  "scripts": {
    "deploy": "NODE_DEBUG=dbg-* nodeshift",
    "start": "node server.js"
  },
```

* I think it is good to have `expose` true by default. It can save developer time searching/understanding why the app is not exposed.

```
  "scripts": {
    "deploy": "NODE_DEBUG=dbg-* nodeshift --expose=true",   <-------
    "start": "node server.js"
  },
```

* Would be good if we remove these warnings:

```console
2020-08-07T11:26:46.783Z TRACE npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-08-07T11:26:47.727Z TRACE npm WARN deprecated har-validator@5.1.5: this library is no longer supported
2020-08-07T11:26:55.744Z TRACE (node:19) Warning: a promise was created in a handler at /usr/lib/node_modules/npm/node_modules/cacache/get.js:159:12 but was not returned from it, see http://goo.gl/rRqMUw
2020-08-07T11:26:55.744Z TRACE at Function.Promise.attempt.Promise.try (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/method.js:29:9)
```

* Without any extra configuration, nodeshift is using Node.js 10x, maybe it should be using 12x ?

```console
2020-08-07T11:26:43.242Z TRACE Using registry.access.redhat.com/ubi8/nodejs-10:latest as the s2i builder image
```

* I don't know what these warnings means, but it seems to be related to the images, so we can't do anything:

```console
2020-08-07T11:26:59.856Z TRACE /opt/app-root/src/.npm is not a mountpoint
2020-08-07T11:27:00.179Z TRACE /tmp is not a mountpoint
```

* Not sure if we need this warning since the app is up and running:

```console
2020-08-07T11:27:03.111Z WARNING No .nodeshift directory
```

* It would be good to have this as a clickable link in terminal:

```console
2020-08-07T11:27:03.154Z INFO route host mapping basic-deploy-myproject.192.168.42.45.nip.io
```

**Comment by lholmquist** [comment]
> I think it is good to have expose true by default. It can save developer time searching/understanding why the app is not exposed.

This is how things use to work,  but then someone mentioned that it is a security risk to have a service exposed by default.  That is why it is the way it is today.   But this is a development tool,  so i don't think it matters if we are exposing by default.  It would be a major version bump if we change it,  but I wouldn't be opposed to making this change.  


> Would be good if we remove these warnings:

I agree,  but the request one is coming from the underlying openshift-rest-client > kubernetes-client dependency.   
Not totally sure about that har-validator though

>  nodeshift is using Node.js 10x, maybe it should be using 12x

Maybe once 10 goes to maintence mode we do this?

> Not sure if we need this warning since the app is up and running:

I wouldn't be opposed to removing this warning.  Again,  i think this was something we did in the beginning because of some reason.  

> I don't know what these warnings means, but it seems to be related to the images, so we can't do anything:

Yea,  those are happening in the cluster and don't have anything to do with Nodeshift

>  It would be good to have this as a clickable link in terminal

Agreed.  I think most terminals will make it clickable if there is the "http/https" on it, which we should be able to get from the Route object

**Comment by helio-frota** [comment]
> This is how things use to work, but then someone mentioned that it is a security risk to have a service exposed by default. That is why it is the way it is today. But this is a development tool, so i don't think it matters if we are exposing by default. It would be a major version bump if we change it, but I wouldn't be opposed to making this change.

I strongly agree. This is a developer tool security stuff should be responsibility of the environment [?] or other situation. But anyway it was good to know the **why**. Thanks.

> I agree, but the request one is coming from the underlying openshift-rest-client > kubernetes-client dependency.
Not totally sure about that har-validator though

:+1:  I remember now the issues with request and etc... The har-validator we can take a look to see what can be done.

> Maybe once 10 goes to maintence mode we do this?

:+1: 

> I wouldn't be opposed to removing this warning. Again, i think this was something we did in the beginning because of some reason.

:+1: 

> Yea, those are happening in the cluster and don't have anything to do with Nodeshift

:+1: 

> Agreed. I think most terminals will make it clickable if there is the "http/https" on it, which we should be able to get from the Route object

I remember we had some discussions on it in the past. For this in particular I'm thinking on a deploy cycle

1) npm run deploy
2) click on the link to see what happened
3) With no need to login on minishift to click on the link

But yeah, we can think on that and or maybe to create an issue

**Comment by helio-frota** [comment]
> The har-validator we can take a look to see what can be done.

request is using that and it is also deprecated 

https://www.npmjs.com/package/har-validator

```
│ └─┬ UNMET DEPENDENCY request@2.88.2
│   ├── UNMET DEPENDENCY aws-sign2@0.7.0
│   ├── UNMET DEPENDENCY aws4@1.10.0
│   ├── UNMET DEPENDENCY caseless@0.12.0
│   ├─┬ UNMET DEPENDENCY combined-stream@1.0.8
│   │ └── UNMET DEPENDENCY delayed-stream@1.0.0
│   ├── UNMET DEPENDENCY extend@3.0.2
│   ├── UNMET DEPENDENCY forever-agent@0.6.1
│   ├─┬ UNMET DEPENDENCY form-data@2.3.3
│   │ ├── UNMET DEPENDENCY asynckit@0.4.0
│   │ ├── UNMET DEPENDENCY combined-stream@1.0.8
│   │ └── UNMET DEPENDENCY mime-types@2.1.27
│   ├─┬ UNMET DEPENDENCY har-validator@5.1.3   <------------------------
```

So nothing todo here, we need to wait kubernetes client's decision about what they are going todo with request :+1: 

Also, going to close this since the other information are saved here as comments
